spring:
  profiles:
    active: dev
  
---
server:
  port: 8001


spring:
  profiles: dev
  application:
    name: springcloud-provider-dept  #3个服务名字一样

#Eureka配置，注册服务到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/,http://192.168.1.8:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001  #修改Eureka上默认的描述信息

---
server:
  port: 8101


spring:
  profiles: test
  application:
    name: springcloud-provider-dept  #3个服务名字一样

#Eureka配置，注册服务到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/,http://192.168.1.8:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001  #修改Eureka上默认的描述信息
